# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Ecoinformatics
description:      'A course for undergraduates covering computational approaches in macroecology'
url:              http://www.datacarpentry.org/semester-biology
baseurl:          /Ecoinformatics
email:            susyelo@gmail.com
author:
  name:           'Susy Echeverría and Drew Kerkhoff'
  url:            https://kerkhofflab.org/

github:
  repo:           https://github.com/GlobalEcologyBiogeography/Ecoinformatics.git
  #               Be sure the 'Issues' feature is activated in 'Settings'
